---
services:
  searxng:
    image: searxng/searxng:latest
    pull_policy: always
    container_name: searxng
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped

  tts:
    image: ghcr.io/matatonic/openedai-speech
    container_name: openedai-speech
    env_file: .tts-env
    ports:
      - 8000:8000
    volumes:
      - ./tts/voices:/app/voices
      - ./tts/config:/app/config
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    container_name: open-webui
    volumes:
      - .open-webui:/app/backend/data
    ports:
      - 8080:8080
      - 11435:11435
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      WEBUI_SECRET_KEY: t00s3cr3t
      ENABLE_SIGNUP: false
      CHUNK_SIZE: 512
      CHUNK_OVERLAP: 50
      ENABLE_RAG_WEB_SEARCH: true
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>
      AUTOMATIC1111_BASE_URL: http://host.docker.internal:7860/
      ENABLE_IMAGE_GENERATION: true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
