---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    volumes:
      - .open-webui:/app/backend/data
    ports:
      - 9999:8080
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      WEBUI_SECRET_KEY: t00s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
