---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    pull_policy: always
    volumes:
      - .open-webui:/app/backend/data
    ports:
      - 8080:8080
      - 11435:11435
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      WEBUI_SECRET_KEY: t00s3cr3t
      ENABLE_SIGNUP: false
      CHUNK_SIZE: 512
      CHUNK_OVERLAP: 50
      # LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      # LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}        
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
