environment_variables:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "1234567890"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "1234567890"
  POSTGRES_DB: "litellm"
  LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
  LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}

general_settings:
  store_model_in_db: true

litellm_settings:
  set_verbose: true
  num_retries: 3
  request_timeout: 60
  fallbacks: [{"ollama/llama3": ["ollama/phi3"]}]
  context_window_fallbacks: [{"ollama/llama3": ["ollama/phi3"]}]
  cache: true
  cache_params:
    type: redis
    ttl: 600
    namespace: "litellm"
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

router_settings:
  routing_strategy: latency-based-routing
  num_retries: 2

model_list:
  - model_name: ollama/phi3
    litellm_params:
      model: ollama/phi3
      api_base: http://host.docker.internal:11434
    model_info:
      mode: completion
  - model_name: ollama/llama3
    litellm_params:
      model: ollama/llama3
      api_base: http://host.docker.internal:11434
    model_info:
      mode: completion

